/**
 * E2E Test Fixtures - JWT Authentication Tokens
 * 
 * Provides JWT token fixtures for authenticated API requests in E2E tests.
 * Includes valid tokens, expired tokens, and invalid tokens for comprehensive
 * authentication testing scenarios. Supports token generation for different
 * user roles (student, teacher, admin).
 * 
 * These tokens are for testing purposes only and use a predictable structure.
 * In real tests, these would be generated by the backend API after successful
 * authentication.
 * 
 * @module tests/e2e/fixtures/auth-tokens
 */

import { jwtDecode } from 'jwt-decode';
import { testStudent } from './users';
import type { User } from './users';

/**
 * Token expiration constants (in seconds)
 * Matches the backend API token configuration
 */
export const ACCESS_TOKEN_EXPIRY = 3600; // 1 hour
export const REFRESH_TOKEN_EXPIRY = 604800; // 7 days

/**
 * JWT token payload structure
 * Represents the decoded token claims as issued by the authentication API
 */
export interface TokenPayload {
  /** Subject - User ID who owns this token */
  sub: number;
  /** Array of role shortnames assigned to the user */
  roles: string[];
  /** Issuer - The Moodle instance that issued this token */
  iss: string;
  /** Issued At - Unix timestamp when token was created */
  iat: number;
  /** Expiration - Unix timestamp when token expires */
  exp: number;
}

/**
 * Authentication token pair
 * Contains both access and refresh tokens for authenticated sessions
 */
export interface AuthTokens {
  /** Short-lived access token for API requests */
  accessToken: string;
  /** Long-lived refresh token for obtaining new access tokens */
  refreshToken: string;
}

/**
 * Base64url encoding helper
 * Converts a string to base64url format (JWT standard encoding)
 * 
 * @param str - String to encode
 * @returns Base64url encoded string
 */
function base64urlEncode(str: string): string {
  // Convert string to base64
  const base64 = Buffer.from(str, 'utf-8').toString('base64');
  
  // Convert to base64url by replacing characters and removing padding
  return base64
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');
}

/**
 * Create a JWT token string from payload
 * Generates a properly formatted JWT with header, payload, and signature.
 * The signature is a fake value for testing purposes.
 * 
 * @param payload - Token payload containing claims
 * @returns JWT token string in format: header.payload.signature
 */
function createJwtToken(payload: TokenPayload): string {
  // JWT header indicating algorithm and token type
  const header = {
    alg: 'HS256',
    typ: 'JWT'
  };
  
  // Encode header and payload as base64url
  const encodedHeader = base64urlEncode(JSON.stringify(header));
  const encodedPayload = base64urlEncode(JSON.stringify(payload));
  
  // For test fixtures, use a predictable fake signature
  // In production, this would be HMAC-SHA256 of header.payload with secret key
  const fakeSignature = base64urlEncode('test_signature_not_cryptographically_valid');
  
  // Combine into standard JWT format
  return `${encodedHeader}.${encodedPayload}.${fakeSignature}`;
}

/**
 * Get current Unix timestamp in seconds
 * @returns Current time as Unix timestamp
 */
function getCurrentTimestamp(): number {
  return Math.floor(Date.now() / 1000);
}

/**
 * Extract role shortnames from user object
 * @param user - User fixture object
 * @returns Array of role shortnames
 */
function extractRoles(user: User): string[] {
  return user.roles.map(role => role.shortname);
}

// Current timestamp for token generation
const now = getCurrentTimestamp();

/**
 * Valid access token for test student
 * Standard access token with 1-hour expiration, suitable for most API request tests
 */
export const validAccessToken = createJwtToken({
  sub: testStudent.id,
  roles: extractRoles(testStudent),
  iss: 'http://localhost:8080',
  iat: now,
  exp: now + ACCESS_TOKEN_EXPIRY
});

/**
 * Valid refresh token for test student
 * Long-lived refresh token with 7-day expiration, used for token refresh tests
 */
export const validRefreshToken = createJwtToken({
  sub: testStudent.id,
  roles: extractRoles(testStudent),
  iss: 'http://localhost:8080',
  iat: now,
  exp: now + REFRESH_TOKEN_EXPIRY
});

/**
 * Expired access token for test student
 * Token that expired 1 hour ago, used for testing token expiration handling
 * and automatic token refresh flows
 */
export const expiredAccessToken = createJwtToken({
  sub: testStudent.id,
  roles: extractRoles(testStudent),
  iss: 'http://localhost:8080',
  iat: now - 7200, // Issued 2 hours ago
  exp: now - 3600  // Expired 1 hour ago
});

/**
 * Invalid token string
 * Malformed token that cannot be decoded, used for testing error handling
 * when invalid tokens are provided to the API
 */
export const invalidToken = 'invalid.token.string';

/**
 * Generate JWT token for specific user
 * Creates a valid JWT token for any user fixture with configurable expiration.
 * Useful for generating tokens on-the-fly during tests for different user roles.
 * 
 * @param user - User fixture object to generate token for
 * @param isRefresh - Whether to generate refresh token (long expiry) or access token (short expiry)
 * @returns JWT token string for the specified user
 * 
 * @example
 * // Generate access token for teacher
 * const teacherToken = generateTokenForUser(testTeacher);
 * 
 * @example
 * // Generate refresh token for admin
 * const adminRefreshToken = generateTokenForUser(testAdmin, true);
 */
export function generateTokenForUser(user: User, isRefresh: boolean = false): string {
  const currentTime = getCurrentTimestamp();
  const expiry = isRefresh ? REFRESH_TOKEN_EXPIRY : ACCESS_TOKEN_EXPIRY;
  
  const payload: TokenPayload = {
    sub: user.id,
    roles: extractRoles(user),
    iss: 'http://localhost:8080',
    iat: currentTime,
    exp: currentTime + expiry
  };
  
  return createJwtToken(payload);
}

/**
 * Decode JWT token to extract payload
 * Parses a JWT token string and returns the decoded payload.
 * Does not verify the signature - use only for testing purposes.
 * 
 * @param token - JWT token string to decode
 * @returns Decoded token payload with user claims
 * @throws Error if token is malformed and cannot be decoded
 * 
 * @example
 * const payload = decodeToken(validAccessToken);
 * console.log(payload.sub); // User ID
 * console.log(payload.roles); // User roles
 */
export function decodeToken(token: string): TokenPayload {
  return jwtDecode<TokenPayload>(token);
}

/**
 * Check if JWT token is expired
 * Validates token expiration by comparing exp claim with current time.
 * Returns true for expired tokens or invalid/malformed tokens.
 * 
 * @param token - JWT token string to validate
 * @returns true if token is expired or invalid, false if still valid
 * 
 * @example
 * if (isTokenExpired(accessToken)) {
 *   // Token expired, need to refresh
 *   const newToken = await refreshAccessToken(refreshToken);
 * }
 */
export function isTokenExpired(token: string): boolean {
  try {
    const payload = decodeToken(token);
    const currentTime = getCurrentTimestamp();
    return payload.exp < currentTime;
  } catch (error) {
    // If token cannot be decoded, consider it expired/invalid
    return true;
  }
}
